//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Go
    {
        public int IDtrain { get; set; }
        public string CityName { get; set; }
        public System.TimeSpan Arrive_Time { get; set; }
    
        public virtual City City { get; set; }
        public virtual Train Train { get; set; }
    }
}
