//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string StartDestination { get; set; }
        public string EndDestination { get; set; }
        public double Price { get; set; }
        public int IDPassenger { get; set; }
        public int SeatID { get; set; }
        public int IDTrain { get; set; }
        public int IDCar { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
